-- MySQL Script generated by MySQL Workbench
-- ned 04 feb 2018 21:20:21 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xml_processor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `xml_processor` ;

-- -----------------------------------------------------
-- Schema xml_processor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xml_processor` DEFAULT CHARACTER SET utf8 ;
USE `xml_processor` ;

-- -----------------------------------------------------
-- Table `xml_processor`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml_processor`.`department` ;

CREATE TABLE IF NOT EXISTS `xml_processor`.`department` (
  `name` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xml_processor`.`doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml_processor`.`doctor` ;

CREATE TABLE IF NOT EXISTS `xml_processor`.`doctor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doctor_department_idx` (`department_name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_doctor_department`
    FOREIGN KEY (`department_name`)
    REFERENCES `xml_processor`.`department` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xml_processor`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml_processor`.`patient` ;

CREATE TABLE IF NOT EXISTS `xml_processor`.`patient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xml_processor`.`disease`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml_processor`.`disease` ;

CREATE TABLE IF NOT EXISTS `xml_processor`.`disease` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xml_processor`.`patient_has_disease`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml_processor`.`patient_has_disease` ;

CREATE TABLE IF NOT EXISTS `xml_processor`.`patient_has_disease` (
  `patient_id` INT NOT NULL,
  `disease_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`patient_id`, `disease_name`),
  INDEX `fk_patient_has_disease_disease1_idx` (`disease_name` ASC),
  INDEX `fk_patient_has_disease_patient1_idx` (`patient_id` ASC),
  CONSTRAINT `fk_patient_has_disease_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `xml_processor`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_has_disease_disease1`
    FOREIGN KEY (`disease_name`)
    REFERENCES `xml_processor`.`disease` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xml_processor`.`document_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml_processor`.`document_report` ;

CREATE TABLE IF NOT EXISTS `xml_processor`.`document_report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `doctor_id` VARCHAR(45) NOT NULL,
  `start` DATETIME NOT NULL,
  `error` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xml_processor`.`doctor_has_patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml_processor`.`doctor_has_patient` ;

CREATE TABLE IF NOT EXISTS `xml_processor`.`doctor_has_patient` (
  `doctor_id` INT NOT NULL,
  `patient_id` INT NOT NULL,
  PRIMARY KEY (`doctor_id`, `patient_id`),
  INDEX `fk_doctor_has_patient_patient1_idx` (`patient_id` ASC),
  INDEX `fk_doctor_has_patient_doctor1_idx` (`doctor_id` ASC),
  CONSTRAINT `fk_doctor_has_patient_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `xml_processor`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_has_patient_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `xml_processor`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
